config/routes.rb
Rails.application.routes.draw do
  root "weather#index"
  post 'forecast', to: 'weather#forecast'
  get '/forecast', to: "weather#index"
  get "weather/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  include HTTParty
  base_uri 'https://api.openweathermap.org/data/2.5'

  def index
  end

  def forecast
    @address  = params[:address ]
    #redirect if address is blank
    return redirect_to root_path, alert: "Please Enter Address" if @address.blank?

    result = Geocoder.search(@address )

    if result.empty?
      return redirect_to root_path, alert: "Invalid Address, Please enter proper address"
    end

    #fetching latitude and longitude based on result
    latitude, longitude = result.first.coordinates 

    #unique key based on address
    cache_key = "weather_#{@address .parameterize}"
    cached_data = Rails.cache.read(cache_key)

    #if cached data present the use it
    if cached_data.present?
      @weather_data = cached_data
      @from_cache = true
    else 
      api_key = ENV['OPENWEATHER_API_KEY']
      api_params =  {
        'lat' => latitude,
        'lon' => longitude,
        'units' => "metric",
        'appid' => api_key
      }

      #fetch weather using openweathermap api
      response = self.class.get("/weather", query: api_params)
      if response.success?
        data = response.parsed_response
        @weather_data = {
          temp: data["main"]["temp"],
          high: data["main"]["temp_max"],
          low: data["main"]["temp_min"],
          description: data["weather"][0]["description"]
        }

        #write to cache for newly fetched weather data
        Rails.cache.write(cache_key, @weather_data, expires_in: 30.minutes)
        @from_cache = false
      else
        return redirect_to root_path, alert: "Unable to fetch forecast data"
      end
    end
    render :index

  end

  def about
    #controller action to show about page
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Weather Forecast', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item" ><%= link_to "About", weather_about_path , class: "nav-link"%></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Weatherapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <% if alert%>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= alert%>
        <%# <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> %>
      </div>
    <%end%>
    
    <%= yield %>
  </body>
</html>

app/views/weather/about.html.erb

<div class="p-3 mb-2 bg-dark-subtle text-dark-emphasis">
  <h1 class="mb-4">Weather Forecast App</h1>

  <p>
    A simple Ruby on Rails application based on the latest version of Ruby-3 and Rails-8
    that fetches weather forecast information using OpenWeatherMap API, caches the previous
    results, and displays the results on search.
  </p>

  <h3 class="mt-4">Usage and Features:</h3>
  <ul>
    <li>Accepts City name or Zip code as input</li>
    <li>Retrieves current temperature along with high/low and weather description</li>
    <li>Caches the results for 30 minutes per address for faster results and displays whether the result is fetched from cache</li>
    <li>Integrated Bootstrap nav bar and components for better styling and has scope to add more features in the future</li>
  </ul>

  <h3 class="mt-4">Tech Stack:</h3>
  <ul>
    <li>Ruby on Rails (LTS)</li>
    <li>Bootstrap 5 for styling</li>
    <li>HTTParty for API requests</li>
    <li>Rails cache</li>
    <li>OpenWeatherMap API key </li>
  </ul>
</div>

app/views/weather/index.html.erb
<br/>
 <%= form_with url: forecast_path, method: :post, local: true, data: { turbo: false }, class: "d-flex", role: "search" do %>
  <%= text_field_tag :address, params[:address], placeholder: "Enter city name or ZIP code", class: "form-control me-2", required: true, aria: { label: "Search" } %>
  <%= submit_tag "Search", class: "btn btn-outline-success" %>
<% end %>
<br/>
<% if @weather_data.present? %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Index</th>
      <th scope="col">Data</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Forecast for</th>
      <td> <%= @address %></td>
    </tr>
    <tr>
      <th scope="row">Temperature</th>
      <td><%= @weather_data[:temp] %>°C</td>
    </tr>
    <tr>
      <th scope="row">Condition</th>
      <td><%= @weather_data[:description] %></td>
    </tr>
    <tr>
      <th scope="row">Highest Temperature</th>
      <td><%= @weather_data[:high] %>°C</td>
    </tr>
    <tr>
      <th scope="row">Lowest Temperature</th>
      <td><%= @weather_data[:low] %>°C</td>
    </tr>
    <tr>
      <th scope="row">Result from cache</th>
      <% if @from_cache %>
        <td class="table-success">Yes</td>
      <% else %>
        <td class="table-danger">No</td>
      <% end %>
    </tr>
  </tbody>
</table>
<% end %>